//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Id { get; set; }
        public string sNombre { get; set; }
        public string sUsuario { get; set; }
        public string sClave { get; set; }
        public int IDRoles { get; set; }
        public string sEMail { get; set; }
        public string sContacto { get; set; }
        public bool bActivo { get; set; }
        public string sTelefono { get; set; }
        public string sCelular { get; set; }
        public string sRFC { get; set; }
        public string sDireccionFiscal { get; set; }
        public bool bDatosActualizados { get; set; }
        public string sExtension { get; set; }
        public string sNombreReprLegal { get; set; }
        public string sNumProveedor { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
